//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalaspphone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public int codMensaje { get; set; }
        public string remitente { get; set; }
        public string destinatario { get; set; }
        public string contenido { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> codRemitente { get; set; }
    
        public virtual Telefono Telefono { get; set; }
    }
}
