//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalaspphone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Telefono()
        {
            this.Mensaje = new HashSet<Mensaje>();
        }
    
        public int codTelefono { get; set; }
        public string nroTelefono { get; set; }
        public Nullable<int> codPersona { get; set; }
        public bool desvio { get; set; }
        public int saldo { get; set; }
        public bool estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensaje> Mensaje { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
